/* ============================================================
   ACG2021 Exam 3 — TESTBANK (src:"B" = Study-Edge / review bank)
   Additional questions from the chapter reviews & session guides,
   hand-verified. {ch, src, ref, q, choices, a, why}
   ============================================================ */

const TESTBANK = [
  /* ---------------- Appendix C ---------------- */
  { ch:"appc", src:"B", ref:"App C · two-option",
    q:"Davenport offers (1) a single signing bonus today, or (2) $30,000 today plus $50,000 two years later. At an 8% time value of money, the single payment in option 1 equal to option 2 is:",
    choices:["$72,867","$80,000","$76,300","$68,587"], a:0,
    why:"Discount each cash flow to today: 30,000 (already today) + 50,000 ÷ 1.08² = 30,000 + 50,000×0.85734 = 30,000 + 42,867 = $72,867." },
  { ch:"appc", src:"B", ref:"App C · FV single",
    q:"How much will $25,000 grow to in 7 years at 12% compounded annually?",
    choices:["$55,267","$46,000","$50,000","$61,000"], a:0,
    why:"FV = 25,000 × 1.12⁷ = 25,000 × 2.21068 = $55,267." },
  { ch:"appc", src:"B", ref:"App C · concept",
    q:"Which combination correctly adjusts a 10% annual rate for MONTHLY compounding over 2 years?",
    choices:["i = 0.8333%, n = 24","i = 10%, n = 2","i = 5%, n = 24","i = 1.2%, n = 12"], a:0,
    why:"Monthly: i = 10% ÷ 12 = 0.8333% per month; n = 2 × 12 = 24 months." },

  /* ---------------- Chapter 9 ---------------- */
  { ch:"ch9", src:"B", ref:"Ch 9 · bond at par issuance",
    q:"Vincent issues $100,000, 10%, 5-year bonds paying interest semiannually; market rate is also 10%. The issuance entry is:",
    choices:["Debit Cash $100,000; Credit Bonds Payable $100,000","Debit Cash $110,000; Credit Bonds Payable $100,000","Debit Bonds Payable $100,000; Credit Cash $100,000","Debit Cash $100,000; Credit Bonds Payable $90,000"], a:0,
    why:"Stated = market, so the bond sells at par (face). Debit Cash and credit Bonds Payable for $100,000." },
  { ch:"ch9", src:"B", ref:"Ch 9 · par bond interest entry",
    q:"Same Vincent par bond ($100,000, 10%, semiannual). The entry on each interest payment date is:",
    choices:["Debit Interest Expense $5,000; Credit Cash $5,000","Debit Interest Expense $10,000; Credit Cash $10,000","Debit Interest Expense $5,000; Credit Bonds Payable $5,000","Debit Cash $5,000; Credit Interest Revenue $5,000"], a:0,
    why:"At par, interest expense = cash = face × stated × ½ = 100,000 × 10% × 6/12 = $5,000. No amortization." },
  { ch:"ch9", src:"B", ref:"Ch 9 · price direction",
    q:"A $500,000 bond issue bears a 10% stated rate while the market rate is 8%. These bonds will sell:",
    choices:["At a premium (above face)","At a discount (below face)","At face value","At a price that can't be determined"], a:0,
    why:"Stated (10%) > market (8%): the above-market coupon is worth extra, so the bond sells at a premium." },
  { ch:"ch9", src:"B", ref:"Ch 9 · carrying value drift",
    q:"How does the carrying value of bonds change over time for bonds issued at a DISCOUNT and at a PREMIUM, respectively?",
    choices:["Discount rises toward face; premium falls toward face","Both rise toward face","Both fall toward face","Discount falls; premium rises"], a:0,
    why:"A discount amortizes UP to face (expense > cash); a premium amortizes DOWN to face (expense < cash). Both end at face." },
  { ch:"ch9", src:"B", ref:"Ch 9 · discount issuance effect",
    q:"A company issues a $20 million bond with a 10% rate for $19,500,000. The bond issuance:",
    choices:["Increases assets and increases liabilities","Increases assets and increases equity","Decreases assets and increases liabilities","Has no effect on the financial statements"], a:0,
    why:"Cash (asset) rises $19.5M and Bonds Payable, net of discount (liability) rises $19.5M. No equity effect at issuance." },
  { ch:"ch9", src:"B", ref:"Ch 9 · read amortization schedule",
    q:"A bond pays $900,000 cash interest every 6 months on a $15,000,000 face amount. What is the STATED ANNUAL rate?",
    choices:["12%","6%","9%","3%"], a:0,
    why:"Semiannual rate = 900,000 ÷ 15,000,000 = 6% per 6 months → annual stated rate = 6% × 2 = 12%." },
  { ch:"ch9", src:"B", ref:"Ch 9 · installment FS effect",
    q:"Issuing an installment note payable to buy equipment has what effect on the financial statements?",
    choices:["Increase assets and increase liabilities","No effect","Increase liabilities and decrease equity","Increase assets and increase equity"], a:0,
    why:"You get equipment (asset ↑) and owe the note (liability ↑). Equity is unaffected." },
  { ch:"ch9", src:"B", ref:"Ch 9 · carrying value highest date",
    q:"Babble Co. signs a five-year installment note on Jan 1, 2024. At which date is the carrying value the HIGHEST?",
    choices:["August 1, 2024","December 31, 2025","November 30, 2026","April 30, 2027"], a:0,
    why:"Carrying value is highest right after signing and falls with every payment, so the earliest date — August 1, 2024 — is highest." },
  { ch:"ch9", src:"B", ref:"Ch 9 · installment interest trend",
    q:"For a ten-year installment note, the interest portion of the payment in the THIRD year is:",
    choices:["More than in the fourth year","Less than in the fourth year","The same as in the fourth year","The same as in the first year"], a:0,
    why:"Interest = balance × rate, and the balance keeps falling, so earlier years have MORE interest. Year 3 interest > year 4 interest." },
  { ch:"ch9", src:"B", ref:"Ch 9 · lease recorded at PV",
    q:"A company can buy equipment for $10,000 or lease it; the lease payments ($182.53/mo) have a present value of $6,000. If it leases, the leased asset is recorded at:",
    choices:["$6,000","$10,000","$6,571","$182.53"], a:0,
    why:"A right-of-use lease asset is recorded at the present value of the lease payments = $6,000 (not the $10,000 purchase price)." },
  { ch:"ch9", src:"B", ref:"Ch 9 · lease balance sheet effect",
    q:"Before a lease: assets $500,000 and liabilities $300,000. The company signs a 30-month lease with payments whose PV is $25,000. After recording the lease it reports:",
    choices:["Assets $525,000 and liabilities $325,000","Assets $500,000 and liabilities $325,000","Assets $525,000 and liabilities $300,000","No change to assets or liabilities"], a:0,
    why:"A recorded lease adds the PV to BOTH sides: assets 500,000+25,000 = 525,000; liabilities 300,000+25,000 = 325,000." },
  { ch:"ch9", src:"B", ref:"Ch 9 · more debt concept",
    q:"Which statement about a company assuming more debt is TRUE?",
    choices:["More debt can be good as long as the return earned exceeds the rate on the borrowed funds","Assuming more debt is always bad","Assuming more debt reduces leverage","Assuming more debt is always good"], a:0,
    why:"This is favorable financial leverage: borrowing helps when the firm earns a return above its borrowing cost." },

  /* ---------------- Chapter 10 ---------------- */
  { ch:"ch10", src:"B", ref:"Ch 10 · treasury reissue below cost",
    q:"A company bought 100 treasury shares at $50, then sells 35 of them at $46. The reissue entry includes:",
    choices:["A $140 reduction of Additional Paid-In Capital–Treasury (then RE)","A $140 loss on the income statement","A $140 credit to APIC–Treasury","A $1,610 credit to Treasury Stock"], a:0,
    why:"Cash 1,610; Treasury credited at cost 1,750; the $140 shortfall reduces APIC–Treasury (then Retained Earnings). Never a loss." },
  { ch:"ch10", src:"B", ref:"Ch 10 · small stock dividend",
    q:"A company declares a 5% stock dividend. The debit to Retained Earnings equals:",
    choices:["The market value of the shares to be issued","The par value of the shares to be issued","The book value of the shares to be issued","The excess of market over original issue price"], a:0,
    why:"A small (<25%) stock dividend capitalizes Retained Earnings at the MARKET value of the new shares." },
  { ch:"ch10", src:"B", ref:"Ch 10 · stock split facts",
    q:"Which statement is NOT true about a 3-for-1 stock split?",
    choices:["Total stockholders' equity increases","The market price per share decreases","A holder of 10 shares ends up with 30 shares","Par value is reduced to one-third"], a:0,
    why:"A split changes share count, par, and price — but total stockholders' equity is UNCHANGED. That statement is false." },
  { ch:"ch10", src:"B", ref:"Ch 10 · large stock dividend (RE transfer)",
    q:"Warren declares a 60% stock dividend on 50,000 shares (market $25, par $10). The retained earnings transferred to common stock is:",
    choices:["$300,000","$750,000","$450,000","$500,000"], a:0,
    why:"60% ≥ 25% = large → use par. New shares 50,000×60% = 30,000 × $10 par = $300,000." },
  { ch:"ch10", src:"B", ref:"Ch 10 · price-earnings",
    q:"Accessories Unlimited: net income $150M, 300M shares, price $20. The price-earnings ratio is:",
    choices:["40","10","20","0.025"], a:0,
    why:"EPS = 150 ÷ 300 = $0.50; P/E = price ÷ EPS = 20 ÷ 0.50 = 40." },

  /* ---------------- Chapter 11 ---------------- */
  { ch:"ch11", src:"B", ref:"Ch 11 · prepaid increase (indirect)",
    q:"If Prepaid Expenses INCREASES during the year, under the indirect method you should:",
    choices:["Subtract the increase from net income — cash was paid out but it isn't an expense yet","Add the increase to net income","Ignore it","Report it under investing activities"], a:0,
    why:"An increase in a current asset uses cash (you prepaid) without reducing net income, so subtract it from net income." },
  { ch:"ch11", src:"B", ref:"Ch 11 · classification check",
    q:"Which of these is a FINANCING activity?",
    choices:["Paying cash dividends to shareholders","Receiving dividends on an investment","Buying equipment","Paying interest on a note"], a:0,
    why:"Dividends PAID = financing. Dividends received and interest paid are operating; buying equipment is investing." },
  { ch:"ch11", src:"B", ref:"Ch 11 · investing classification",
    q:"Collecting the principal on a note receivable you lent out is classified as:",
    choices:["Investing activity","Operating activity","Financing activity","Non-cash disclosure"], a:0,
    why:"Lending and collecting note principal is investing. (Any interest collected on it is operating.)" },
  { ch:"ch11", src:"B", ref:"Ch 11 · non-cash transaction",
    q:"A company buys equipment with a fair value of $150,000 by paying $25,000 cash and signing a note for the rest. On the statement of cash flows:",
    choices:["$25,000 is an investing outflow; the $125,000 note is a non-cash disclosure","$150,000 is an investing outflow","$125,000 is a financing inflow","Nothing is reported"], a:0,
    why:"Only the $25,000 cash paid is an investing outflow; the $125,000 financed by the note is disclosed separately as a non-cash investing/financing activity." }
];
